### ISSUE TITLE
Feature request: integrate salint rules

### ISSUE THREAD

**Issue by max-arnold** [roaldnefs/salt-lint#19]
What do you think about integrating all rules from the (unmaintained) [salint](https://github.com/gtmanfred/salint/) package into salt-lint?

It is able to catch things like this one:

```yaml
test:
  file.touch:
    - name: /tmp/test
    - require:
      - test: test2
    - wathc_in:     # <-- typo here, should be watch_in
      - service: some-service
```

Also, it would be nice to be able to inject custom config values here https://github.com/gtmanfred/salint/blob/master/salint/script.py#L17 and specify pillar/grain fixtures.

**Comment by roaldnefs** [comment]
Thanks @max-arnold for your feature request!

I'm going to take a stab at a PR in the upcoming days, I've been thinking about a feature like this since the beginning of salt-lint.

**Comment by roaldnefs** [comment]
I'm now able to locally render the state which would be able to catch errors in simple states. There are however a few disadvantages to rendering the states:
- Rendering the states would cost a lot of time (_couple of seconds per state_).
- `salt-lint` needs to be executed from the location where the `top.sls` lives (_would require a workaround to work on formulas, which don't contain a `top.sls`_).
- States wrapped within a Jinja statement (_see example below_) would require the grain and pillar data to be available for `salt-lint`, because I see a lot of projects using a `pillar.example` we might want to automatically load any existing `pillar.example` file and figure out how to can supply the required grains data.
```yaml
{% if salt['pillar.get']('test') %}
test:
  file.touch:
    - name: /tmp/test
    - require:
      - test: test2
    - wathc_in:     # <-- typo here, should be watch_in
      - service: some-service
{% endif %}
```

While I still would like to implement this feature, I don't think all `salt-lint` users would like to wait for a state to be rendered each time. Therefore I'm thinking about making the rendering part opt-in (_requiring a flag to be set before it runs_).

To allow somewhat more complex rules, I'm also working om a YAML renderer in #37. Using this feature we can easily add rules to check for deprecated options and for things like `cmd.wait` which could be found for both the standard declaration and inline function declaration, e.g.:

```yaml
{% if salt['pillar.get']('test') %}
test:
  cmd:          # standard declaration
    - wait
    - name: mycommand
    ...

test:
  cmd.wait:   # inline function declaration
    - name: mycommand
    ...
{% endif %}
```
